server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://ott-db:3306/odb?serverTimezone=Asia/Seoul
    username: ottp
    password: ottp
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false